# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "YABOONG"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Safety zone is unsafe - Yaboong"

# Tagline near the site title
tagline: "Safety zone is unsafe."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://yaboong.github.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Categories
  url: /categories
- text: Tags
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: yaboong-github-io

# Author information - author info at the bottom of the post
author_name: "Yaboong"
author_bio: "오스카 쉰들러는 흔해빠진 기회주의자요 부패한 사업가였다. 그러나 거대한 악이 세상을 점령하는 것처럼 보일 때 그 악에 대항해서 사람의 생명을 구한 것은 귀족도 지식인도 종교인도 아닌 부패한 기회주의자 오스카 쉰들러였다."
author_url:  "https://github.com/yaboong"
author_location: "Seoul, South Korea"
author_image: /images/yaboong.jpeg

# Sidebar Add banner
banner_url: "https://github.com/yaboong"
banner_image: images/yaboong.jpeg
banner_prefix: "/yaboong-blog-static-resources/banner/"

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
# facebook_username: "yabooong"
# googleplus_username: "u/0/101688448325229683345"
github_username: "yaboong"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
# instagram_username: "yaboooong"
#pinterest_username: "username"
#linkedin_username: "username"
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude:
  - node_modules

# Google Analytics
google_analytics: UA-113745841-1

# for ffmpeg
include:
  - assets
  - _pages
webrick:
  headers:
    Cross-Origin-Opener-Policy: same-origin
    Cross-Origin-Embedder-Policy: require-corp
