# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "YABOONG"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Flying Yaboong | Byte to Flight"

# Tagline near the site title
tagline: "Done with coding, ready for takeoff ✈️"
# My code finally took off
# From code to cockpit
# Beyond the code, into the clouds
# Code to Clouds
# My code finally took off


# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://yaboong.github.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Categories
  url: /categories
- text: Tags
  url: /tags/

# The shortname for your Disqus site to enable comments.
# disqus: yaboong-github-io
disqus: false

# Author information - author info at the bottom of the post
author_name: "Yaboong"
author_bio: "Oskar Schindler was a mere opportunist and a corrupt businessman. Yet, when it seemed that great evil was taking over the world, it was not nobles, intellectuals, or religious leaders who rose to defy it and save lives—it was a corrupt opportunist, Oskar Schindler."
author_url:  "https://github.com/yaboong"
author_location: "Massachusetts, US"
author_image: /images/yaboong.jpeg
author_linkedin: "https://www.linkedin.com/in/yebonyou/"
author_email: "daniel.yebon.you@gmail.com"

# Sidebar Add banner
banner_url: "https://github.com/yaboong"
banner_image: images/yaboong.jpeg
banner_prefix: "/yaboong-blog-static-resources/banner/"

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
#twitter_username: "username"
# facebook_username: "yabooong"
# googleplus_username: "u/0/101688448325229683345"
github_username: "yaboong"
#codepen_username: "username"
#dribbble_uername: "username"
#medium_username: "@username"
# instagram_username: "yaboooong"
#pinterest_username: "username"
#linkedin_username: "username"
#weibo_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/blog/page:num/'
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude:
  - node_modules

# Google Analytics
google_analytics: UA-113745841-1

# for ffmpeg
include:
  - assets
  - _pages
